# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "puphpet/centos65-x64"

  config.vm.network "private_network", ip: "192.168.33.17"

  config.vm.synced_folder "../shared/www", "/var/www"

  #Scripts
  config.vm.provision "shell", path: "scripts/install_modules.sh"

  #Puppet
  config.vm.provision :puppet do |puppet|
    puppet.environment_path = "environments"
    puppet.environment      = "development"
    puppet.manifests_path = "environments/development/manifests"
    puppet.manifest_file  = "site.pp"
    puppet.module_path    = "modules"
  end

end
